version: 2

registries:
  github-teamjtharrison:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}

updates:
 - package-ecosystem: "terraform"
   directory: "/"
   registries:
     - github-teamjtharrison
   schedule:
     interval: "daily"
